### PR TITLE
List structure

### PR DESCRIPTION
**Pull request by TEMESGEN-G25**
## To do list structure

In this project I:
- Set up a the project with webpack.
- Set an array of some simple to do tasks (array of objects).
- Written a function to iterate over the tasks array and populate an HTML list item element for each task.
- All source files (index.html, index.js and style.css) are located in /src directory and the distribution files are generated by webpack and served by webpack dev server from /dist folder.

### CODE REVIEW

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi @NatiG25,** 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

- Linters are passing.
- The Code is clean.
- PR is really nice.


## Required Changes ♻️
_Check the comments under the review._


- Hello my friend you have done really great work you missed just one step that you didn't add details about the project in the readme file. please do so and ask again for a review.


### **Optional**

- You can add an option `mode: development or production` in your webpack file. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by NatiG25** [comment]
[dasileker](https://github.com/dasileker) Thank you for your suggestion.

**Comment by TEMESGEN-G25** [comment]
Thank you for suggestion [dasileker](https://github.com/dasileker).

**Review by Mihndim2020 — APPROVED** [review]
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @NatiG25, 

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

Congratulations-Memes-FEATURED

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
